--liquibase formatted sql

--changeset lebedev:001-create-users
CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    removed    BOOLEAN                  NOT NULL DEFAULT FALSE,

    type       VARCHAR(20)              NOT NULL
);

--rollback DROP TABLE users;