--liquibase formatted sql

--changeset lebedev:002-create-car-head
CREATE TABLE car_head
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    removed    BOOLEAN                  NOT NULL DEFAULT FALSE,

    brand      VARCHAR(50)              NOT NULL,
    model      VARCHAR(100)             NOT NULL,
    body_type  VARCHAR(50)              NOT NULL
);

--rollback DROP TABLE car_head;