--liquibase formatted sql

--changeset lebedev:003-create-car-version
CREATE TABLE car_version
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at              TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at              TIMESTAMP WITH TIME ZONE NOT NULL,
    removed                 BOOLEAN                  NOT NULL DEFAULT FALSE,

    name                    VARCHAR(255)             NOT NULL,
    car_head_id             BIGINT                   NOT NULL,
    engine_fuel_type        VARCHAR(20)              NOT NULL,
    engine_power_hp         BIGINT                   NOT NULL,
    engine_capacity_liters  FLOAT                    NOT NULL,
    gearbox_type            VARCHAR(20)              NOT NULL,
    car_drive               VARCHAR(20)              NOT NULL,
    price_rubles            NUMERIC(12, 2)           NOT NULL CHECK (price_rubles >= 0),
    is_test_drive_available BOOLEAN                  NOT NULL DEFAULT FALSE,

    CONSTRAINT fk_car_version_head
        FOREIGN KEY (car_head_id) REFERENCES car_head (id)
            ON DELETE CASCADE
);

--rollback DROP TABLE car_version;