--liquibase formatted sql

--changeset lebedev:005-create-detail
CREATE TABLE detail
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    removed      BOOLEAN                  NOT NULL DEFAULT FALSE,

    name         VARCHAR(255)             NOT NULL,
    type         VARCHAR(100)             NOT NULL,
    price_rubles NUMERIC(12, 2)           NOT NULL CHECK (price_rubles >= 0)
);

--rollback DROP TABLE detail;