--liquibase formatted sql

--changeset lebedev:007-create-car-configuration-defaulter
CREATE TABLE car_configuration_defaulter
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    removed        BOOLEAN                  NOT NULL DEFAULT FALSE,

    car_version_id BIGINT                   NOT NULL,

    CONSTRAINT fk_car_configuration_defaulter_car_version
        FOREIGN KEY (car_version_id) REFERENCES car_version (id)
            ON DELETE CASCADE
);

--rollback DROP TABLE users;