--liquibase formatted sql

--changeset lebedev:009-create-car-configuration-customizer
CREATE TABLE car_configuration_customizer
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    removed        BOOLEAN                  NOT NULL DEFAULT FALSE,

    user_id        BIGINT                   NOT NULL,
    car_version_id BIGINT                   NOT NULL,

    CONSTRAINT fk_car_configuration_customizer_user
        FOREIGN KEY (user_id) REFERENCES users (id)
            ON DELETE CASCADE,

    CONSTRAINT fk_car_configuration_customizer_car_version
        FOREIGN KEY (car_version_id) REFERENCES car_version (id)
            ON DELETE CASCADE
);

--rollback DROP TABLE users;