--liquibase formatted sql

--changeset lebedev:012-create-car-configuration
CREATE TABLE car_configuration
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    removed        BOOLEAN                  NOT NULL DEFAULT FALSE,

    user_id        BIGINT                   NOT NULL,
    car_version_id BIGINT                   NOT NULL,

    CONSTRAINT fk_car_configuration_user
        FOREIGN KEY (user_id) REFERENCES users (id),

    CONSTRAINT fk_car_configuration_car_version
        FOREIGN KEY (car_version_id) REFERENCES car_version (id)
);
--rollback DROP TABLE car_configuration;