--liquibase formatted sql

--changeset lebedev:014-create-test-drive
CREATE TABLE test_drive
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    removed        BOOLEAN                  NOT NULL DEFAULT FALSE,

    user_id        BIGINT                   NOT NULL,
    car_version_id BIGINT                   NOT NULL,
    date_time      TIMESTAMP WITH TIME ZONE NOT NULL,

    CONSTRAINT fk_test_drive_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,

    CONSTRAINT fk_test_drive_car_version
        FOREIGN KEY (car_version_id) REFERENCES car_version (id)
);

--rollback DROP TABLE test_drive;