--liquibase formatted sql

--changeset lebedev:015-create-stock-order
CREATE TABLE stock_order
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    removed        BOOLEAN                  NOT NULL DEFAULT FALSE,

    user_id        BIGINT                   NOT NULL,
    car_version_id BIGINT                   NOT NULL,
    status         VARCHAR(30)              NOT NULL,

    CONSTRAINT fk_stock_order_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,

    CONSTRAINT fk_stock_order_car_version
        FOREIGN KEY (car_version_id) REFERENCES car_version (id)
);

--rollback DROP TABLE stock_order;