--liquibase formatted sql

--changeset lebedev:016-create-configured-car-order
CREATE TABLE configured_car_order
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at           TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at           TIMESTAMP WITH TIME ZONE NOT NULL,
    removed              BOOLEAN                  NOT NULL DEFAULT FALSE,

    car_configuration_id BIGINT                   NOT NULL,

    status               VARCHAR(30)              NOT NULL,

    CONSTRAINT fk_configured_car_order_configuration
        FOREIGN KEY (car_configuration_id) REFERENCES car_configuration (id)
            ON DELETE CASCADE
);

--rollback DROP TABLE configured_car_order;