spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.config.import=
spring.docker.compose.enabled=false

spring.datasource.driver-class-name=org.postgresql.Driver
spring.liquibase.enabled=true